/**
 * Enum for the type of periodicity of the regularity
 */
export enum PeriodicityType {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  BIWEEKLY = 'BIWEEKLY',
  MONTHLY = 'MONTHLY',
  BIMONTHLY = 'BIMONTHLY',
  QUARTERLY = 'QUARTERLY',
  SEMI_ANNUAL = 'SEMI_ANNUAL',
  YEARLY = 'YEARLY',
  OTHER = 'OTHER',
}

/**
 * Enum for the repartition type
 */
export enum RepartitionType {
  HAS_BEGUN_AND_STOPPED_DURING_ANALYSIS = 'HAS_BEGUN_AND_STOPPED_DURING_ANALYSIS',
  HAS_STOPPED_BEFORE_END_OF_ANALYSIS = 'HAS_STOPPED_BEFORE_END_OF_ANALYSIS',
  HAS_BEGUN_AFTER_START_OF_ANALYSIS = 'HAS_BEGUN_AFTER_START_OF_ANALYSIS',
  HAS_NOT_CHANGED_DURING_ANALYSIS = 'HAS_NOT_CHANGED_DURING_ANALYSIS',
}
