/**
 * Enum for the income categories
 */
export enum TransactionIncomeCategory {
  ALLOWANCE = 'ALLOWANCE',
  ALLOWANCE_FAMILY = 'ALLOWANCE_FAMILY',
  ALLOWANCE_HOUSING = 'ALLOWANCE_HOUSING',
  ALLOWANCE_UNEMPLOYMENT = 'ALLOWANCE_UNEMPLOYMENT',
  ALLOWANCE_HEALTH = 'ALLOWANCE_HEALTH',
  ALLOWANCE_INCOME_SUPPORT = 'ALLOWANCE_INCOME_SUPPORT',
  STATE_SUBSIDY = 'STATE_SUBSIDY',
  GAMBLING_GAIN = 'GAMBLING_GAIN',
  RENTAL_INCOME = 'RENTAL_INCOME',
  RECEIVED_ALIMONY = 'RECEIVED_ALIMONY',
  WAGE = 'WAGE',
  WAGE_BONUS = 'WAGE_BONUS',
  WAGE_SALARY_ADVANCE = 'WAGE_SALARY_ADVANCE',
  WAGE_ADVANCE_PAYMENT = 'WAGE_ADVANCE_PAYMENT',
  RETIREMENT_PENSION = 'RETIREMENT_PENSION',
  REVERSIONARY_PENSION = 'REVERSIONARY_PENSION',
  DISSAVING = 'DISSAVING',
  OTHER_ENTRY = 'OTHER_ENTRY',
}

/**
 * Enum for the expense categories
 */
export enum TransactionExpenseCategory {
  INSURANCE = 'INSURANCE',
  INSURANCE_HEALTH = 'INSURANCE_HEALTH',
  INSURANCE_AUTO = 'INSURANCE_AUTO',
  INSURANCE_HOME = 'INSURANCE_HOME',
  TRANSPORT = 'TRANSPORT',
  POWER = 'POWER',
  RENT = 'RENT',
  TELECOM = 'TELECOM',
  HEALTH = 'HEALTH',
  GROCERY = 'GROCERY',
  TOBACCO = 'TOBACCO',
  GAMBLING = 'GAMBLING',
  LEISURE = 'LEISURE',
  SHOPPING = 'SHOPPING',
  DEFERRED_TOTAL_PAYMENT = 'DEFERRED_TOTAL_PAYMENT',
  MULTIMEDIA = 'MULTIMEDIA',
  SPORT = 'SPORT',
  OTHER_EXPENSE = 'OTHER_EXPENSE',
}

/**
 * Enum for the credit categories
 */
export enum TransactionCreditCategory {
  LOAN_DRAWDOWN = 'LOAN_DRAWDOWN',
  LOAN_DRAWDOWN_REAL_ESTATE = 'LOAN_DRAWDOWN_REAL_ESTATE',
  LOAN_DRAWDOWN_PERSONAL = 'LOAN_DRAWDOWN_PERSONAL',
  LOAN_DRAWDOWN_REVOLVING = 'LOAN_DRAWDOWN_REVOLVING',
  LOAN_REPAYMENT = 'LOAN_REPAYMENT',
  LOAN_REPAYMENT_REAL_ESTATE = 'LOAN_REPAYMENT_REAL_ESTATE',
  LOAN_REPAYMENT_PERSONAL = 'LOAN_REPAYMENT_PERSONAL',
  LOAN_REPAYMENT_REVOLVING = 'LOAN_REPAYMENT_REVOLVING',
  LOAN_PREPAYMENT = 'LOAN_PREPAYMENT',
  SPLIT_PAYMENT = 'SPLIT_PAYMENT',
  DEBT_RECOVERY = 'DEBT_RECOVERY',
  DEBT_COLLECTION = 'DEBT_COLLECTION',
  BAILIFF = 'BAILIFF',
  LEASING = 'LEASING',
}

/**
 * Enum for the saving categories
 */
export enum TransactionSavingCategory {
  INTEREST = 'INTEREST',
  SAVING = 'SAVING',
  BANKBOOK_SAVING = 'BANKBOOK_SAVING',
  SHARE_SAVING = 'SHARE_SAVING',
}

/**
 * Enum for the bank operation categories
 */
export enum TransactionBankOperationCategory {
  REJECTION_PAYMENT = 'REJECTION_PAYMENT',
  REJECTION_LOAN_REPAYMENT = 'REJECTION_LOAN_REPAYMENT',
  REJECTION_CHECK = 'REJECTION_CHECK',
  FEES_BANK_SERVICE = 'FEES_BANK_SERVICE',
  FEES_OVERDRAFT = 'FEES_OVERDRAFT',
  FEES_CHECK_REJECTION = 'FEES_CHECK_REJECTION',
  FEES_PAYMENT_REJECTION = 'FEES_PAYMENT_REJECTION',
  FEES_INTERVENTION = 'FEES_INTERVENTION',
  FEES_INCIDENT = 'FEES_INCIDENT',
  FEES_DIRECT_DEBT_RECOVERY = 'FEES_DIRECT_DEBT_RECOVERY',
  FEES_ACCOUNT_SEIZURE = 'FEES_ACCOUNT_SEIZURE',
  FEES_PREVENTIVE_SEIZURE = 'FEES_PREVENTIVE_SEIZURE',
  REFUND_DIRECT_DEBT_RECOVERY_FEES = 'REFUND_DIRECT_DEBT_RECOVERY_FEES',
  REFUND_ACCOUNT_SEIZURE_FEES = 'REFUND_ACCOUNT_SEIZURE_FEES',
  REFUND_PREVENTIVE_SEIZURE_FEES = 'REFUND_PREVENTIVE_SEIZURE_FEES',
  REFUND_BANK_INCIDENT_FEES = 'REFUND_BANK_INCIDENT_FEES',
  REFUND_BANK_SERVICE_FEES = 'REFUND_BANK_SERVICE_FEES',
  RELEASE_DIRECT_DEBT_RECOVERY = 'RELEASE_DIRECT_DEBT_RECOVERY',
  RELEASE_ACCOUNT_SEIZURE = 'RELEASE_ACCOUNT_SEIZURE',
  RELEASE_PREVENTIVE_SEIZURE = 'RELEASE_PREVENTIVE_SEIZURE',
  PROVISION_DIRECT_DEBT_RECOVERY = 'PROVISION_DIRECT_DEBT_RECOVERY',
  PROVISION_ACCOUNT_SEIZURE = 'PROVISION_ACCOUNT_SEIZURE',
  PROVISION_PREVENTIVE_SEIZURE = 'PROVISION_PREVENTIVE_SEIZURE',
  CREDIT_CARD_RESET = 'CREDIT_CARD_RESET',
}

/**
 * Enum for refund categories
 */
export enum TransactionRefundCategory {
  REFUND = 'REFUND',
  REFUND_INSURANCE = 'REFUND_INSURANCE',
  REFUND_EXPENSE_REPORT = 'REFUND_EXPENSE_REPORT',
}

/**
 * Enum for tax category
 */
export enum TransactionTaxCategory {
  PRO_TAX = 'PRO_TAX',
  PRO_TAX_REFUND = 'PRO_TAX_REFUND',
  PERSO_TAX = 'PERSO_TAX',
  INCOME_TAX = 'INCOME_TAX',
  HOUSING_TAX = 'HOUSING_TAX',
  PROPERTY_TAX = 'PROPERTY_TAX',
  PERSO_TAX_CREDIT = 'PERSO_TAX_CREDIT',
  PERSO_TAX_REFUND = 'PERSO_TAX_REFUND',
}

/**
 * Temporary categories. Will be removed after DS implements needed algos
 */
export enum TransactionTemporaryCategory {
  /**
   * @deprecated
   */
  REGULAR_INCOME = 'REGULAR_INCOME',
  /**
   * @deprecated
   */
  REGULAR_EXPENSE = 'REGULAR_EXPENSE',
}

/**
 * Enum for the transactions type
 */
export enum TransactionType {
  CASH_DEPOSIT = 'CASH_DEPOSIT',
  CASH_WITHDRAWAL = 'CASH_WITHDRAWAL',
  CHECK_DEPOSIT = 'CHECK_DEPOSIT',
  CHECK = 'CHECK',
  INCOMING_TRANSFER = 'INCOMING_TRANSFER',
  INCOMING_INTERNAL_TRANSFER = 'INCOMING_INTERNAL_TRANSFER',
  OUTGOING_TRANSFER = 'OUTGOING_TRANSFER',
  OUTGOING_INTERNAL_TRANSFER = 'OUTGOING_INTERNAL_TRANSFER',
  CARD = 'CARD',
  CARD_REFUND = 'CARD_REFUND',
  DIRECT_DEBIT = 'DIRECT_DEBIT',
  INCOMING_CARD = 'INCOMING_CARD',
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
}
