module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  coverageDirectory: 'coverage',
  coverageReporters: ['json', 'lcov'],
  coverageThreshold: {
    global: {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 0,
    },
  },
  collectCoverageFrom: [
    'src/**/*.{js,ts}',
    '!**/node_modules/**',
    '!src/lib/index.ts',
    '!src/lib/Account.enum.ts',
    '!src/lib/Account.interface.ts',
    '!src/lib/Aggregator.interface.ts',
    '!src/lib/Analysis.enum.ts',
    '!src/lib/Analysis.interface.ts',
    '!src/lib/Calendar.interface.ts',
    '!src/lib/CreditInsights.enum.ts',
    '!src/lib/CreditInsights.interface.ts',
    '!src/lib/Customer.enum.ts',
    '!src/lib/Customer.interface.ts',
    '!src/lib/Score.interface.ts',
    '!src/lib/Transaction.enum.ts',
    '!src/lib/Transaction.interface.ts',
  ],
};
