#! /usr/bin/env node
const { program } = require('commander');

const { Algoan } = require('../dist/src');

program
  .requiredOption('-u, --url <url>', 'Sandbox Base Url')
  .requiredOption('-c, --client-id <clientId>', 'Your service client id')
  .requiredOption('-s, --secret <secret>', 'Your service client secret')
  .parse(process.argv);

/**
 * Fetch all service accounts
 */
async function fetchServiceAccounts() {
  const algoanClient = new Algoan({
    baseUrl: program.url,
    clientId: program.clientId,
    clientSecret: program.secret,
  });

  return algoanClient.getServiceAccounts();
}

fetchServiceAccounts()
  .then((serviceAccounts) => {
    console.log(serviceAccounts);
  })
  .catch((err) => {
    console.error(err);
  })
  .finally(() => {
    process.exit(0);
  })